/**
 * Expanded Coral Species Data
 * Sprint 28: Species Database Upgrade
 */

import type { SpeciesSeed } from "../seed-species-types";

export const coralsExpanded: SpeciesSeed[] = [
  // ============================================================================
  // SOFT CORALS
  // ============================================================================
  {
    common_name: "Xenia",
    scientific_name: "Xenia elongata",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - relies on zooxanthellae",
    compatibility_notes: "Fast grower, can become invasive. Give it its own rock.",
    description: "Pulsing soft coral with hypnotic pumping polyps.",
    lifespan_years: 20,
    origin_region: "Indo-Pacific",
    habitat: "Shallow reef flats",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Can spread rapidly - isolate on own rock", "Pulsing indicates health"],
    fun_facts: ["One of few corals that actively pulses", "Scientists still don't know why it pulses"],
    aliases: ["Pulsing Xenia", "Pulse Coral"]
  },
  {
    common_name: "Kenya Tree Coral",
    scientific_name: "Capnella sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 16,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can also absorb dissolved organics",
    compatibility_notes: "Prolific grower. Drops branches that reattach and grow.",
    description: "Tree-shaped soft coral that propagates by dropping branches.",
    lifespan_years: 20,
    origin_region: "Indo-Pacific, Red Sea",
    habitat: "Various reef zones",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Self-propagates by dropping branches", "Can become invasive"],
    fun_facts: ["Dropped branches root themselves on nearby rocks"],
    aliases: ["Broccoli Coral", "Tree Leather"]
  },
  {
    common_name: "Toadstool Leather Coral",
    scientific_name: "Sarcophyton sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 18,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - may benefit from occasional feeding",
    compatibility_notes: "Releases toxins - run carbon and give space from SPS.",
    description: "Mushroom-shaped leather coral with fuzzy polyps.",
    lifespan_years: 30,
    origin_region: "Indo-Pacific",
    habitat: "Reef lagoons and slopes",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Sheds waxy coating periodically - normal", "Run activated carbon"],
    fun_facts: ["Can grow to over a foot across in home aquariums"],
    aliases: ["Mushroom Leather", "Toadstool"]
  },
  {
    common_name: "Sinularia Leather",
    scientific_name: "Sinularia sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 15,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic",
    compatibility_notes: "Hardy leather coral. Less toxic than Sarcophyton.",
    description: "Finger-like leather coral with various growth forms.",
    lifespan_years: 25,
    origin_region: "Indo-Pacific",
    habitat: "Various reef zones",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["More tolerant than most leathers", "Easy to frag"],
    fun_facts: ["Available in many colors including green, yellow, and pink"],
    aliases: ["Finger Leather", "Cabbage Coral"]
  },
  // ============================================================================
  // MUSHROOM CORALS (CORALLIMORPHS)
  // ============================================================================
  {
    common_name: "Discosoma Mushroom",
    scientific_name: "Discosoma sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 4,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can catch small particles",
    compatibility_notes: "Very hardy. Can spread and overgrow other corals.",
    description: "Classic disc-shaped mushroom coral in many colors.",
    lifespan_years: 15,
    origin_region: "Indo-Pacific, Caribbean",
    habitat: "Shaded reef areas",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Prefers lower light", "Will multiply on its own"],
    fun_facts: ["Technically not a true coral but a corallimorph"],
    aliases: ["Disc Anemone", "Mushroom Anemone"]
  },
  {
    common_name: "Ricordea Mushroom",
    scientific_name: "Ricordea florida",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 3,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can catch small foods",
    compatibility_notes: "Hardy and colorful. Slower growing than Discosoma.",
    description: "Bubble-textured mushroom in stunning color morphs.",
    lifespan_years: 15,
    origin_region: "Caribbean",
    habitat: "Shallow reef rubble",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Tolerates moderate light", "Rare morphs can be very expensive"],
    fun_facts: ["Rainbow and Yuma varieties can sell for hundreds of dollars"],
    aliases: ["Florida Ricordea", "Flower Mushroom"]
  },
  {
    common_name: "Rhodactis Mushroom",
    scientific_name: "Rhodactis sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 20,
    max_size_inches: 8,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - will catch and eat fish if hungry",
    compatibility_notes: "Can eat small fish and shrimp. Give space.",
    description: "Large, fuzzy mushroom that can catch prey.",
    lifespan_years: 15,
    origin_region: "Indo-Pacific",
    habitat: "Various reef zones",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "carnivore",
    feeding_frequency: "Weekly if desired",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Can eat small fish - be cautious", "Grows large quickly"],
    fun_facts: ["Has been known to eat clownfish!"],
    aliases: ["Hairy Mushroom", "Elephant Ear Mushroom"]
  },
  // ============================================================================
  // ZOANTHIDS & PALYTHOAS
  // ============================================================================
  {
    common_name: "Zoanthid",
    scientific_name: "Zoanthus sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 6,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can catch small particles",
    compatibility_notes: "Hardy, colorful, and easy. Can spread rapidly.",
    description: "Colonial polyps in endless color combinations.",
    lifespan_years: 20,
    origin_region: "Worldwide tropical",
    habitat: "Reef flats and rubble",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["CAUTION: Some contain palytoxin - don't handle roughly", "Very collectible"],
    fun_facts: ["Designer morphs have creative names and high prices"],
    aliases: ["Zoas", "Zoos", "Button Polyps"]
  },
  {
    common_name: "Palythoa",
    scientific_name: "Palythoa sp.",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 8,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can catch larger particles",
    compatibility_notes: "Similar to zoas but larger polyps. Contains palytoxin.",
    description: "Larger polyps than zoanthids, often brown/green.",
    lifespan_years: 20,
    origin_region: "Worldwide tropical",
    habitat: "Shallow reef areas",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["CAUTION: Contains highly toxic palytoxin", "Never handle with cuts on hands"],
    fun_facts: ["Palytoxin is one of the most toxic substances known"],
    aliases: ["Palys", "Sea Mat"]
  },
  // ============================================================================
  // LPS CORALS
  // ============================================================================
  {
    common_name: "Hammer Coral",
    scientific_name: "Euphyllia ancora",
    type: "coral",
    care_level: "intermediate",
    temperament: "aggressive",
    min_tank_size_gallons: 50,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - spot feed meaty foods weekly",
    compatibility_notes: "Has sweeper tentacles. Give 6+ inches from other corals.",
    description: "Popular LPS with hammer-shaped tentacle tips.",
    lifespan_years: 30,
    origin_region: "Indo-Pacific",
    habitat: "Protected reef slopes",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "1-2x weekly",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Related to torch - don't touch together", "Needs moderate flow"],
    fun_facts: ["Can host clownfish like an anemone"],
    aliases: ["Anchor Coral", "Euphyllia Hammer"]
  },
  {
    common_name: "Frogspawn Coral",
    scientific_name: "Euphyllia divisa",
    type: "coral",
    care_level: "intermediate",
    temperament: "aggressive",
    min_tank_size_gallons: 50,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - benefits from target feeding",
    compatibility_notes: "Sweeper tentacles can sting neighbors.",
    description: "Branch-tipped Euphyllia resembling frog eggs.",
    lifespan_years: 30,
    origin_region: "Indo-Pacific",
    habitat: "Reef slopes with moderate flow",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "1-2x weekly",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Branch-form Euphyllia", "Don't mix with torch or hammer directly"],
    fun_facts: ["Branching structure makes it easy to frag"],
    aliases: ["Frogspawn", "Octospawn"]
  },
  {
    common_name: "Duncan Coral",
    scientific_name: "Duncanopsammia axifuga",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - eagerly accepts meaty foods",
    compatibility_notes: "Very peaceful LPS. Easy to keep and propagate.",
    description: "Easy LPS with daisy-like polyps that readily feeds.",
    lifespan_years: 25,
    origin_region: "Australia",
    habitat: "Deeper reef slopes",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "carnivore",
    feeding_frequency: "2-3x weekly",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["One of the easiest LPS", "Loves to eat - grow faster with regular feeding"],
    fun_facts: ["Polyps look like underwater daisies"],
    aliases: ["Whisker Coral", "Duncanops"]
  },
  {
    common_name: "Candy Cane Coral",
    scientific_name: "Caulastrea furcata",
    type: "coral",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 10,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - can be target fed but not required",
    compatibility_notes: "Very peaceful. One of the easiest LPS corals.",
    description: "Branching LPS with candy-striped appearance.",
    lifespan_years: 25,
    origin_region: "Indo-Pacific",
    habitat: "Various reef zones",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Very forgiving", "Easy to frag between branches"],
    fun_facts: ["Also called Trumpet Coral for branch shape"],
    aliases: ["Trumpet Coral", "Bullseye Coral"]
  },
  {
    common_name: "Acan Lord",
    scientific_name: "Micromussa lordhowensis",
    type: "coral",
    care_level: "intermediate",
    temperament: "aggressive",
    min_tank_size_gallons: 20,
    max_size_inches: 8,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - grows much faster when fed",
    compatibility_notes: "Moderate sweepers. Give space from other corals.",
    description: "Colorful encrusting LPS available in rainbow of colors.",
    lifespan_years: 20,
    origin_region: "Australia",
    habitat: "Reef slopes",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2-3x weekly",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Feeding dramatically increases growth", "Lower light brings out colors"],
    fun_facts: ["Designer color morphs can cost thousands"],
    aliases: ["Acan", "Lord Coral", "Micromussa"]
  },
  {
    common_name: "Brain Coral",
    scientific_name: "Lobophyllia sp.",
    type: "coral",
    care_level: "intermediate",
    temperament: "aggressive",
    min_tank_size_gallons: 50,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic + carnivore - loves meaty foods",
    compatibility_notes: "Has sweeper tentacles at night. Give space.",
    description: "Large fleshy coral resembling a brain.",
    lifespan_years: 30,
    origin_region: "Indo-Pacific",
    habitat: "Reef lagoons",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2x weekly",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Sweeper tentacles emerge at night", "Feed when tentacles are out"],
    fun_facts: ["Can grow to basketball size in the wild"],
    aliases: ["Lobed Brain Coral", "Lobo"]
  },
  // ============================================================================
  // SPS CORALS
  // ============================================================================
  {
    common_name: "Montipora",
    scientific_name: "Montipora sp.",
    type: "coral",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 50,
    max_size_inches: 24,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - high light, stable parameters required",
    compatibility_notes: "Easier SPS. Good stepping stone to acropora.",
    description: "Easiest SPS coral, available in plating and encrusting forms.",
    lifespan_years: 30,
    origin_region: "Indo-Pacific",
    habitat: "Reef slopes and flats",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Most forgiving SPS", "Stable parameters more important than perfection"],
    fun_facts: ["Montipora capricornis creates beautiful plating structures"],
    aliases: ["Monti", "Velvet Coral"]
  },
  {
    common_name: "Acropora",
    scientific_name: "Acropora sp.",
    type: "coral",
    care_level: "expert",
    temperament: "peaceful",
    min_tank_size_gallons: 75,
    max_size_inches: 24,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - demands high light, pristine water",
    compatibility_notes: "The pinnacle of reef keeping. Very demanding.",
    description: "The iconic branching reef coral - challenging but rewarding.",
    lifespan_years: 50,
    origin_region: "Worldwide tropical",
    habitat: "Reef crests with high light and flow",
    group_behavior: "colony",
    breeding_difficulty: "difficult",
    diet_type: "photosynthetic",
    salinity_min: 1.025,
    salinity_max: 1.026,
    care_tips: ["Needs pristine water quality", "High flow and high light essential"],
    fun_facts: ["Builds the majority of natural coral reefs"],
    aliases: ["Acro", "SPS", "Staghorn Coral"]
  },
  {
    common_name: "Birdsnest Coral",
    scientific_name: "Seriatopora hystrix",
    type: "coral",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 50,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic - moderate SPS requirements",
    compatibility_notes: "Easier SPS. Fast growing once established.",
    description: "Delicate branching SPS that resembles a bird's nest.",
    lifespan_years: 25,
    origin_region: "Indo-Pacific",
    habitat: "Reef slopes",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Easier than Acropora", "Fast grower once adapted"],
    fun_facts: ["Available in pink, green, and yellow varieties"],
    aliases: ["Needle Coral", "Seriatopora"]
  },
  {
    common_name: "Stylophora",
    scientific_name: "Stylophora pistillata",
    type: "coral",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 50,
    max_size_inches: 10,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Photosynthetic",
    compatibility_notes: "Hardy SPS with thick branches.",
    description: "Thick-branched SPS coral, hardier than most acros.",
    lifespan_years: 25,
    origin_region: "Indo-Pacific, Red Sea",
    habitat: "Reef slopes",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    salinity_min: 1.024,
    salinity_max: 1.026,
    care_tips: ["Good beginner SPS", "Thick branches make it more resilient"],
    fun_facts: ["Often hosts small gobies and shrimp in its branches"],
    aliases: ["Cat's Paw Coral", "Stylo"]
  }
];
