/**
 * Expanded Freshwater Fish Species Data
 * Sprint 28: Species Database Upgrade
 */

import type { SpeciesSeed } from "../seed-species-types";

export const freshwaterFishExpanded: SpeciesSeed[] = [
  // ============================================================================
  // TETRAS (Additional)
  // ============================================================================
  {
    common_name: "Black Skirt Tetra",
    scientific_name: "Gymnocorymbus ternetzi",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 15,
    max_size_inches: 2.5,
    temp_min_f: 70,
    temp_max_f: 85,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods",
    compatibility_notes: "May nip at long-finned fish. Keep in groups of 5+.",
    description: "Hardy tetra with distinctive black coloring and flowing fins.",
    lifespan_years: 5,
    origin_region: "Paraguay, Bolivia",
    habitat: "Slow-moving rivers and tributaries",
    group_behavior: "schooling",
    min_school_size: 5,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 20,
    care_tips: ["Very hardy species", "Can be fin nippers - avoid slow tankmates"],
    fun_facts: ["Color fades with age", "Also available in long-fin variety"],
    aliases: ["Black Widow Tetra", "Petticoat Tetra"]
  },
  {
    common_name: "Ember Tetra",
    scientific_name: "Hyphessobrycon amandae",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 0.8,
    temp_min_f: 73,
    temp_max_f: 84,
    ph_min: 5.5,
    ph_max: 7.0,
    diet: "Omnivore - micro pellets, crushed flakes, baby brine shrimp",
    compatibility_notes: "Tiny and peaceful. Perfect for nano tanks and shrimp tanks.",
    description: "Tiny, bright orange tetra that glows like an ember in planted tanks.",
    lifespan_years: 4,
    origin_region: "Araguaia River Basin, Brazil",
    habitat: "Slow-moving blackwater streams",
    group_behavior: "schooling",
    min_school_size: 8,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 1,
    hardness_max_dgh: 10,
    care_tips: ["Ideal for planted nano tanks", "Color intensifies in darker setups"],
    fun_facts: ["One of the smallest tetras in the hobby", "Named after Amanda Bleher"],
    aliases: ["Fire Tetra", "Amanda's Tetra"]
  },
  {
    common_name: "Congo Tetra",
    scientific_name: "Phenacogrammus interruptus",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 3.5,
    temp_min_f: 73,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - quality flakes, frozen foods, live foods",
    compatibility_notes: "Peaceful but needs space. Males are stunning with flowing fins.",
    description: "Large, iridescent tetra with rainbow colors and flowing finnage.",
    lifespan_years: 5,
    origin_region: "Congo River Basin, Africa",
    habitat: "Streams and tributaries with moderate current",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 3,
    hardness_max_dgh: 18,
    care_tips: ["Needs swimming space", "Males develop spectacular fins"],
    fun_facts: ["One of the largest and most colorful tetras"],
    aliases: ["Blue Congo Tetra"]
  },
  {
    common_name: "Serpae Tetra",
    scientific_name: "Hyphessobrycon eques",
    type: "freshwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 20,
    max_size_inches: 1.75,
    temp_min_f: 72,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods",
    compatibility_notes: "Can be nippy. Keep in larger groups to reduce aggression.",
    description: "Deep red tetra with black markings. Active and bold.",
    lifespan_years: 5,
    origin_region: "Amazon Basin",
    habitat: "Slow-moving waters with vegetation",
    group_behavior: "schooling",
    min_school_size: 8,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Columnaris"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 25,
    care_tips: ["Keep in larger groups to reduce fin nipping", "Avoid slow-moving tankmates"],
    fun_facts: ["Also called Blood Characin", "Color deepens with good diet"],
    aliases: ["Red Minor Tetra", "Jewel Tetra", "Blood Characin"]
  },
  {
    common_name: "Lemon Tetra",
    scientific_name: "Hyphessobrycon pulchripinnis",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 15,
    max_size_inches: 2,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 5.5,
    ph_max: 8.0,
    diet: "Omnivore - flakes, small pellets, frozen foods",
    compatibility_notes: "Very peaceful. Great community fish.",
    description: "Translucent yellow tetra with striking red eyes.",
    lifespan_years: 6,
    origin_region: "Amazon Basin, Brazil",
    habitat: "Slow-moving tributaries",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 3,
    hardness_max_dgh: 20,
    care_tips: ["Color intensifies in mature specimens", "Very adaptable to water conditions"],
    fun_facts: ["Eye color indicates health - bright red means healthy"],
    aliases: []
  },
  {
    common_name: "Diamond Tetra",
    scientific_name: "Moenkhausia pittieri",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 2.5,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods",
    compatibility_notes: "Peaceful schooling fish. Stunning in planted tanks.",
    description: "Sparkling silver tetra that shimmers like diamonds under light.",
    lifespan_years: 5,
    origin_region: "Lake Valencia, Venezuela",
    habitat: "Lake margins with vegetation",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 4,
    hardness_max_dgh: 15,
    care_tips: ["Best displayed under good lighting", "Needs some swimming space"],
    fun_facts: ["Endemic to a single lake in Venezuela"],
    aliases: ["Pittier's Tetra"]
  },
  // ============================================================================
  // BARBS
  // ============================================================================
  {
    common_name: "Tiger Barb",
    scientific_name: "Puntigrus tetrazona",
    type: "freshwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 20,
    max_size_inches: 3,
    temp_min_f: 74,
    temp_max_f: 79,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods, vegetables",
    compatibility_notes: "Keep in groups of 8+ to reduce fin nipping. Avoid slow tankmates.",
    description: "Active, boldly striped barb that's been a hobby favorite for decades.",
    lifespan_years: 6,
    origin_region: "Sumatra, Borneo",
    habitat: "Clear forest streams",
    group_behavior: "schooling",
    min_school_size: 8,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet", "Columnaris"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Keep in large groups to reduce aggression", "Very active - needs swimming room"],
    fun_facts: ["Available in many color morphs including green and albino"],
    aliases: ["Sumatra Barb"]
  },
  {
    common_name: "Cherry Barb",
    scientific_name: "Puntius titteya",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 15,
    max_size_inches: 2,
    temp_min_f: 73,
    temp_max_f: 81,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Omnivore - flakes, small pellets, frozen foods",
    compatibility_notes: "One of the most peaceful barbs. Excellent community fish.",
    description: "Beautiful red barb that intensifies color when breeding.",
    lifespan_years: 5,
    origin_region: "Sri Lanka",
    habitat: "Shaded streams with leaf litter",
    group_behavior: "small_group",
    min_school_size: 5,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 19,
    care_tips: ["Males are more colorful than females", "Shy at first, gains confidence in groups"],
    fun_facts: ["Listed as vulnerable in the wild due to habitat loss"],
    aliases: []
  },
  {
    common_name: "Rosy Barb",
    scientific_name: "Pethia conchonius",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 6,
    temp_min_f: 64,
    temp_max_f: 77,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, vegetables, frozen foods",
    compatibility_notes: "Peaceful but active. Needs space due to size.",
    description: "Large, colorful barb with males showing intense pink/red coloring.",
    lifespan_years: 5,
    origin_region: "India, Bangladesh",
    habitat: "Fast-flowing streams and rivers",
    group_behavior: "schooling",
    min_school_size: 5,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Gill Flukes"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 19,
    care_tips: ["Tolerates cooler temperatures", "Can be kept in unheated tanks in some climates"],
    fun_facts: ["Males turn bright red when breeding"],
    aliases: ["Red Barb"]
  },
  {
    common_name: "Denison Barb",
    scientific_name: "Sahyadria denisonii",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 55,
    max_size_inches: 6,
    temp_min_f: 65,
    temp_max_f: 77,
    ph_min: 6.5,
    ph_max: 7.8,
    diet: "Omnivore - quality pellets, frozen foods, vegetables",
    compatibility_notes: "Active swimmer needing lots of space. Keep in groups.",
    description: "Stunning torpedo-shaped barb with red, black, and yellow markings.",
    lifespan_years: 8,
    origin_region: "Western Ghats, India",
    habitat: "Fast-flowing hill streams",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "very_difficult",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Bacterial Infections"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 25,
    care_tips: ["Needs high oxygen levels", "Prefers cooler water with good flow"],
    fun_facts: ["Also known as Miss Kerala - named after the Indian state"],
    aliases: ["Roseline Shark", "Miss Kerala", "Red Line Torpedo Barb"]
  },
  // ============================================================================
  // RASBORAS
  // ============================================================================
  {
    common_name: "Harlequin Rasbora",
    scientific_name: "Trigonostigma heteromorpha",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2,
    temp_min_f: 73,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - flakes, micro pellets, frozen foods",
    compatibility_notes: "Perfect community fish. Peaceful with everything.",
    description: "Classic aquarium fish with distinctive triangular black patch.",
    lifespan_years: 6,
    origin_region: "Malaysia, Singapore, Thailand",
    habitat: "Forest streams with soft, acidic water",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 2,
    hardness_max_dgh: 12,
    care_tips: ["One of the best beginner fish", "Beautiful in planted tanks"],
    fun_facts: ["Was one of the first tropical fish imported to Europe"],
    aliases: ["Red Rasbora"]
  },
  {
    common_name: "Chili Rasbora",
    scientific_name: "Boraras brigittae",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 0.7,
    temp_min_f: 68,
    temp_max_f: 82,
    ph_min: 4.0,
    ph_max: 7.0,
    diet: "Omnivore - micro foods, baby brine shrimp, crushed flakes",
    compatibility_notes: "Tiny fish best kept with other nano species or shrimp.",
    description: "Tiny jewel-like fish with intense red coloration.",
    lifespan_years: 4,
    origin_region: "Borneo, Indonesia",
    habitat: "Blackwater peat swamps",
    group_behavior: "schooling",
    min_school_size: 10,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 1,
    hardness_max_dgh: 5,
    care_tips: ["Needs soft, acidic water for best color", "Keep with small peaceful tankmates only"],
    fun_facts: ["One of the smallest aquarium fish available"],
    aliases: ["Mosquito Rasbora", "Brigittae Rasbora"]
  },
  {
    common_name: "Scissortail Rasbora",
    scientific_name: "Rasbora trilineata",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 5,
    temp_min_f: 72,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods",
    compatibility_notes: "Active schooling fish. Needs swimming space.",
    description: "Larger rasbora with distinctive scissor-like tail movement.",
    lifespan_years: 5,
    origin_region: "Thailand, Malaysia, Sumatra",
    habitat: "Rivers and streams",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Needs a longer tank for swimming", "Very active jumper - keep lid on"],
    fun_facts: ["Named for the scissor-like movement of its tail"],
    aliases: ["Three-lined Rasbora"]
  },
  // ============================================================================
  // GOURAMIS
  // ============================================================================
  {
    common_name: "Dwarf Gourami",
    scientific_name: "Trichogaster lalius",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 3.5,
    temp_min_f: 77,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Omnivore - flakes, pellets, frozen foods, algae",
    compatibility_notes: "Peaceful but males may be territorial. One male per tank.",
    description: "Stunning small gourami with brilliant red and blue striping.",
    lifespan_years: 4,
    origin_region: "India, Bangladesh",
    habitat: "Slow-moving, vegetated waters",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Dwarf Gourami Disease (DGD)", "Ich", "Fin Rot"],
    hardness_min_dgh: 4,
    hardness_max_dgh: 15,
    care_tips: ["Buy from reputable sources to avoid DGD", "Males are more colorful"],
    fun_facts: ["Builds bubble nests at the surface", "Can breathe atmospheric air"],
    aliases: ["Flame Gourami", "Powder Blue Gourami", "Neon Blue Gourami"]
  },
  {
    common_name: "Pearl Gourami",
    scientific_name: "Trichopodus leerii",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 5,
    temp_min_f: 77,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Omnivore - flakes, pellets, frozen foods, vegetables",
    compatibility_notes: "Very peaceful gourami. Excellent community fish.",
    description: "Elegant gourami covered in pearlescent spots with a black stripe.",
    lifespan_years: 5,
    origin_region: "Thailand, Malaysia, Sumatra",
    habitat: "Acidic swamps and slow streams",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet", "Bacterial Infections"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 25,
    care_tips: ["One of the most peaceful gouramis", "Males develop red breast when breeding"],
    fun_facts: ["Considered one of the most beautiful gouramis"],
    aliases: ["Lace Gourami", "Mosaic Gourami"]
  },
  {
    common_name: "Honey Gourami",
    scientific_name: "Trichogaster chuna",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - small pellets, flakes, frozen foods",
    compatibility_notes: "Extremely peaceful. Can be shy - provide hiding spots.",
    description: "Small, peaceful gourami with honey-colored body.",
    lifespan_years: 5,
    origin_region: "India, Bangladesh",
    habitat: "Densely vegetated waters",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 4,
    hardness_max_dgh: 15,
    care_tips: ["More disease-resistant than Dwarf Gouramis", "Shy at first but gains confidence"],
    fun_facts: ["Males turn bright orange when breeding"],
    aliases: ["Sunset Gourami", "Red Honey Gourami"]
  },
  // ============================================================================
  // CATFISH
  // ============================================================================
  {
    common_name: "Bristlenose Pleco",
    scientific_name: "Ancistrus sp.",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 5,
    temp_min_f: 73,
    temp_max_f: 81,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Herbivore - algae wafers, vegetables, driftwood",
    compatibility_notes: "Excellent algae eater. Peaceful with all tankmates.",
    description: "The best algae-eating pleco that stays small enough for most tanks.",
    lifespan_years: 12,
    origin_region: "Amazon Basin, South America",
    habitat: "Fast-flowing streams with driftwood",
    group_behavior: "solitary",
    breeding_difficulty: "moderate",
    diet_type: "herbivore",
    feeding_frequency: "1x daily + constant algae grazing",
    common_diseases: ["Ich", "Bacterial Infections"],
    hardness_min_dgh: 6,
    hardness_max_dgh: 20,
    care_tips: ["Needs driftwood for digestion", "Supplement with vegetables like zucchini"],
    fun_facts: ["Males grow distinctive bristles on their nose", "Can live 15+ years"],
    aliases: ["Bushynose Pleco", "BN Pleco"]
  },
  {
    common_name: "Otocinclus",
    scientific_name: "Otocinclus vittatus",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2,
    temp_min_f: 72,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Herbivore - algae, algae wafers, blanched vegetables",
    compatibility_notes: "Peaceful but sensitive. Best in established, planted tanks.",
    description: "Tiny algae-eating catfish perfect for planted tanks.",
    lifespan_years: 5,
    origin_region: "South America",
    habitat: "Clear streams with algae-covered surfaces",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "difficult",
    diet_type: "herbivore",
    feeding_frequency: "Constant grazing, supplement 1x daily",
    common_diseases: ["Starvation", "Ich"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Only add to established tanks with algae", "May need supplemental feeding"],
    fun_facts: ["One of the most efficient algae eaters for small tanks"],
    aliases: ["Oto Catfish", "Dwarf Suckermouth"]
  },
  {
    common_name: "Pygmy Corydoras",
    scientific_name: "Corydoras pygmaeus",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1,
    temp_min_f: 72,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - micro foods, sinking pellets, frozen foods",
    compatibility_notes: "Tiny and peaceful. Perfect for nano tanks.",
    description: "Miniature corydoras that hovers mid-water unlike other species.",
    lifespan_years: 3,
    origin_region: "Amazon Basin",
    habitat: "Sandy-bottomed streams",
    group_behavior: "schooling",
    min_school_size: 8,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Bacterial Infections"],
    hardness_min_dgh: 2,
    hardness_max_dgh: 15,
    care_tips: ["Unlike other corys, swims in mid-water", "Keep in larger groups"],
    fun_facts: ["One of the smallest corydoras species"],
    aliases: ["Pygmy Cory"]
  },
  {
    common_name: "Julii Corydoras",
    scientific_name: "Corydoras julii",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 2.5,
    temp_min_f: 73,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.8,
    diet: "Omnivore - sinking pellets, frozen foods, algae wafers",
    compatibility_notes: "Peaceful bottom dweller. Keep in groups.",
    description: "Attractive spotted corydoras with leopard-like pattern.",
    lifespan_years: 8,
    origin_region: "Brazil",
    habitat: "Sandy river bottoms",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "1-2x daily",
    common_diseases: ["Ich", "Red Blotch Disease"],
    hardness_min_dgh: 2,
    hardness_max_dgh: 18,
    care_tips: ["Often confused with C. trilineatus", "Needs sand substrate"],
    fun_facts: ["True julii corys are rare - most sold are trilineatus"],
    aliases: ["Leopard Cory"]
  },
  // ============================================================================
  // DANIOS & MINNOWS
  // ============================================================================
  {
    common_name: "Zebra Danio",
    scientific_name: "Danio rerio",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2,
    temp_min_f: 64,
    temp_max_f: 77,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Omnivore - flakes, pellets, frozen foods",
    compatibility_notes: "Very active swimmer. May stress slow-moving fish.",
    description: "Classic beginner fish with horizontal blue stripes.",
    lifespan_years: 5,
    origin_region: "India, Bangladesh",
    habitat: "Streams and rice paddies",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet", "Mycobacteriosis"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 19,
    care_tips: ["Extremely hardy", "Very active - needs horizontal swimming space"],
    fun_facts: ["Used extensively in genetic research", "First pet fish in space"],
    aliases: ["Zebrafish"]
  },
  {
    common_name: "Celestial Pearl Danio",
    scientific_name: "Danio margaritatus",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1,
    temp_min_f: 72,
    temp_max_f: 78,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Omnivore - micro foods, baby brine shrimp, crushed flakes",
    compatibility_notes: "Shy fish best kept with other small, peaceful species.",
    description: "Stunning micro fish with galaxy-like spotted pattern.",
    lifespan_years: 5,
    origin_region: "Myanmar",
    habitat: "Small vegetated ponds",
    group_behavior: "small_group",
    min_school_size: 6,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Can be shy - provide plants for cover", "Males spar but rarely cause harm"],
    fun_facts: ["Only discovered in 2006", "Nearly became endangered due to overcollection"],
    aliases: ["Galaxy Rasbora", "CPD", "Fireworks Rasbora"]
  },
  {
    common_name: "White Cloud Mountain Minnow",
    scientific_name: "Tanichthys albonubes",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1.5,
    temp_min_f: 64,
    temp_max_f: 72,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Omnivore - flakes, small pellets, frozen foods",
    compatibility_notes: "Hardy coldwater fish. Can be kept without heater.",
    description: "Hardy minnow with iridescent stripe and red fins.",
    lifespan_years: 5,
    origin_region: "China",
    habitat: "Mountain streams",
    group_behavior: "schooling",
    min_school_size: 6,
    breeding_difficulty: "easy",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Fin Rot"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 20,
    care_tips: ["Prefers cooler water", "Great alternative to tropical fish"],
    fun_facts: ["Thought to be extinct in the wild until recently rediscovered"],
    aliases: ["WCMM", "Canton Danio"]
  },
  // ============================================================================
  // KILLIFISH
  // ============================================================================
  {
    common_name: "Clown Killifish",
    scientific_name: "Epiplatys annulatus",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 1.5,
    temp_min_f: 68,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 7.0,
    diet: "Carnivore - live/frozen foods, will accept small pellets",
    compatibility_notes: "Surface dweller. Keep with small peaceful fish.",
    description: "Tiny killifish with striped body and rocket-shaped tail.",
    lifespan_years: 3,
    origin_region: "West Africa",
    habitat: "Forest streams and swamps",
    group_behavior: "small_group",
    min_school_size: 4,
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Velvet"],
    hardness_min_dgh: 3,
    hardness_max_dgh: 10,
    care_tips: ["Surface dweller - needs floating plants", "Good jumper - keep tank covered"],
    fun_facts: ["Also called Rocket Killifish for tail shape"],
    aliases: ["Banded Panchax", "Rocket Killifish"]
  },
  // ============================================================================
  // LOACHES
  // ============================================================================
  {
    common_name: "Kuhli Loach",
    scientific_name: "Pangio kuhlii",
    type: "freshwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 4,
    temp_min_f: 75,
    temp_max_f: 86,
    ph_min: 5.5,
    ph_max: 7.0,
    diet: "Omnivore - sinking pellets, frozen foods, live foods",
    compatibility_notes: "Nocturnal and shy. Provide hiding spots.",
    description: "Eel-like loach with striking orange and brown bands.",
    lifespan_years: 10,
    origin_region: "Southeast Asia",
    habitat: "Sandy stream bottoms",
    group_behavior: "small_group",
    min_school_size: 5,
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "1x daily (evening)",
    common_diseases: ["Ich", "Skinny Disease"],
    hardness_min_dgh: 1,
    hardness_max_dgh: 10,
    care_tips: ["Needs soft sand substrate", "Mostly nocturnal - may hide during day"],
    fun_facts: ["Can squeeze into tiny spaces", "Often found in filter intakes"],
    aliases: ["Coolie Loach", "Leopard Loach"]
  },
  {
    common_name: "Clown Loach",
    scientific_name: "Chromobotia macracanthus",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 125,
    max_size_inches: 12,
    temp_min_f: 77,
    temp_max_f: 86,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - sinking pellets, frozen foods, snails",
    compatibility_notes: "Peaceful but grows very large. Keep in groups.",
    description: "Colorful, popular loach that gets much bigger than most expect.",
    lifespan_years: 20,
    origin_region: "Borneo, Sumatra",
    habitat: "Rivers and flooded forests",
    group_behavior: "schooling",
    min_school_size: 5,
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Skinny Disease"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Grows very large - needs big tank long-term", "Excellent snail control"],
    fun_facts: ["Can make clicking sounds", "Lives 20+ years in good conditions"],
    aliases: ["Tiger Loach"]
  },
  {
    common_name: "Yoyo Loach",
    scientific_name: "Botia almorhae",
    type: "freshwater",
    care_level: "intermediate",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 40,
    max_size_inches: 6,
    temp_min_f: 75,
    temp_max_f: 86,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Omnivore - sinking pellets, frozen foods, snails",
    compatibility_notes: "Can be boisterous. Keep in groups to spread aggression.",
    description: "Active loach with Y-O-Y-O pattern on its body.",
    lifespan_years: 10,
    origin_region: "India, Pakistan",
    habitat: "Rivers and streams",
    group_behavior: "small_group",
    min_school_size: 4,
    breeding_difficulty: "very_difficult",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Ich", "Skinny Disease"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Very active", "Excellent pest snail control"],
    fun_facts: ["Named for the Y-O-Y-O pattern on juvenile fish"],
    aliases: ["Pakistani Loach", "Almora Loach"]
  }
];
