/**
 * Expanded Invertebrate Species Data
 * Sprint 28: Species Database Upgrade
 */

import type { SpeciesSeed } from "../seed-species-types";

export const invertebratesExpanded: SpeciesSeed[] = [
  // ============================================================================
  // FRESHWATER SHRIMP
  // ============================================================================
  {
    common_name: "Blue Dream Shrimp",
    scientific_name: "Neocaridina davidi var. blue",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 1.5,
    temp_min_f: 65,
    temp_max_f: 80,
    ph_min: 6.5,
    ph_max: 8.0,
    diet: "Omnivore - biofilm, algae, shrimp pellets, vegetables",
    compatibility_notes: "Keep away from large or aggressive fish. Breed readily.",
    description: "Stunning blue color variant of the cherry shrimp.",
    lifespan_years: 2,
    origin_region: "Taiwan (selectively bred)",
    habitat: "Freshwater streams and ponds",
    group_behavior: "colony",
    min_school_size: 10,
    breeding_difficulty: "easy",
    diet_type: "detritivore",
    feeding_frequency: "1x daily",
    common_diseases: ["Vorticella", "Muscular Necrosis", "Bacterial Infections"],
    hardness_min_dgh: 4,
    hardness_max_dgh: 14,
    care_tips: ["No copper-based medications", "Higher grade = more intense blue"],
    fun_facts: ["Selectively bred from wild brown Neocaridina"],
    aliases: ["Blue Velvet Shrimp", "Blue Diamond Shrimp"]
  },
  {
    common_name: "Crystal Red Shrimp",
    scientific_name: "Caridina cantonensis",
    type: "invertebrate",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1.25,
    temp_min_f: 68,
    temp_max_f: 76,
    ph_min: 5.8,
    ph_max: 6.8,
    diet: "Omnivore - biofilm, algae, shrimp-specific foods",
    compatibility_notes: "Sensitive species. Keep in species-only tank.",
    description: "Striking red and white banded shrimp prized by collectors.",
    lifespan_years: 2,
    origin_region: "Taiwan (selectively bred from Hong Kong)",
    habitat: "Soft, acidic waters",
    group_behavior: "colony",
    min_school_size: 6,
    breeding_difficulty: "moderate",
    diet_type: "detritivore",
    feeding_frequency: "1x daily",
    common_diseases: ["Bacterial Infections", "Molting Issues"],
    hardness_min_dgh: 0,
    hardness_max_dgh: 6,
    care_tips: ["Needs remineralized RO water", "Very sensitive to parameter swings"],
    fun_facts: ["SSS grade can sell for hundreds of dollars"],
    aliases: ["CRS", "Bee Shrimp"]
  },
  {
    common_name: "Ghost Shrimp",
    scientific_name: "Palaemonetes paludosus",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 2,
    temp_min_f: 65,
    temp_max_f: 80,
    ph_min: 7.0,
    ph_max: 8.0,
    diet: "Omnivore - algae, detritus, sinking foods",
    compatibility_notes: "Hardy and inexpensive. Often sold as feeder shrimp.",
    description: "Nearly transparent shrimp, excellent for beginners and cleanup.",
    lifespan_years: 1,
    origin_region: "North America",
    habitat: "Freshwater streams and ponds",
    group_behavior: "small_group",
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "1x daily",
    common_diseases: ["Bacterial Infections", "Parasites"],
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Very hardy and forgiving", "Larvae need brackish water to survive"],
    fun_facts: ["You can see their internal organs through the shell"],
    aliases: ["Glass Shrimp", "Grass Shrimp"]
  },
  {
    common_name: "Bamboo Shrimp",
    scientific_name: "Atyopsis moluccensis",
    type: "invertebrate",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 4,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Filter feeder - needs water flow with particles, can supplement with powder foods",
    compatibility_notes: "Peaceful filter feeder. Needs good water flow.",
    description: "Large, fascinating shrimp that filter feeds from the water column.",
    lifespan_years: 3,
    origin_region: "Southeast Asia",
    habitat: "Fast-flowing streams",
    group_behavior: "small_group",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "filter_feeder",
    feeding_frequency: "Constant filter feeding",
    common_diseases: ["Molting Issues", "Starvation"],
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Needs current to filter feed", "If digging in substrate, it's starving"],
    fun_facts: ["Has fan-like appendages to catch food particles"],
    aliases: ["Wood Shrimp", "Asian Filter Shrimp", "Flower Shrimp"]
  },
  // ============================================================================
  // FRESHWATER SNAILS
  // ============================================================================
  {
    common_name: "Mystery Snail",
    scientific_name: "Pomacea bridgesii",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 2.5,
    temp_min_f: 68,
    temp_max_f: 84,
    ph_min: 7.0,
    ph_max: 8.0,
    diet: "Omnivore - algae, vegetables, calcium supplements",
    compatibility_notes: "Peaceful. Great cleaners. Will not reproduce in freshwater alone.",
    description: "Large, colorful apple snail in many color varieties.",
    lifespan_years: 1,
    origin_region: "South America",
    habitat: "Slow-moving waters",
    group_behavior: "solitary",
    breeding_difficulty: "easy",
    diet_type: "herbivore",
    feeding_frequency: "Constant grazing, supplement 2-3x weekly",
    common_diseases: ["Shell Erosion", "Parasites"],
    hardness_min_dgh: 8,
    hardness_max_dgh: 18,
    care_tips: ["Needs calcium for shell health", "Lays eggs above waterline"],
    fun_facts: ["Available in gold, blue, ivory, purple, and more"],
    aliases: ["Apple Snail", "Spike-Topped Apple Snail"]
  },
  {
    common_name: "Assassin Snail",
    scientific_name: "Clea helena",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1.25,
    temp_min_f: 75,
    temp_max_f: 80,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Carnivore - pest snails, meaty foods, sinking pellets",
    compatibility_notes: "Will hunt pest snails. Safe with larger snails.",
    description: "Attractive striped snail that hunts and eats pest snails.",
    lifespan_years: 3,
    origin_region: "Southeast Asia",
    habitat: "Slow-moving streams with sandy bottom",
    group_behavior: "solitary",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "When pest snails available, else 2-3x weekly",
    common_diseases: ["Parasites"],
    hardness_min_dgh: 4,
    hardness_max_dgh: 15,
    care_tips: ["Excellent for pest snail control", "Will eat shrimp if hungry"],
    fun_facts: ["Uses proboscis to suck out prey from shells"],
    aliases: ["Snail-Eating Snail", "Bumblebee Snail"]
  },
  {
    common_name: "Ramshorn Snail",
    scientific_name: "Planorbella duryi",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 1,
    temp_min_f: 70,
    temp_max_f: 80,
    ph_min: 7.0,
    ph_max: 8.0,
    diet: "Omnivore - algae, detritus, vegetables",
    compatibility_notes: "Prolific breeder. Can overpopulate if overfed.",
    description: "Flat, spiral-shelled snail available in many colors.",
    lifespan_years: 2,
    origin_region: "Worldwide (invasive)",
    habitat: "Freshwater ponds and slow streams",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "herbivore",
    feeding_frequency: "Constant grazing",
    common_diseases: ["Shell Erosion"],
    hardness_min_dgh: 5,
    hardness_max_dgh: 15,
    care_tips: ["Control population by not overfeeding", "Great algae cleaners"],
    fun_facts: ["Breathes both air and water", "Available in red, blue, pink, leopard"],
    aliases: ["Ram's Horn Snail"]
  },
  // ============================================================================
  // SALTWATER INVERTEBRATES
  // ============================================================================
  {
    common_name: "Cleaner Shrimp",
    scientific_name: "Lysmata amboinensis",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - parasites from fish, meaty foods, pellets",
    compatibility_notes: "Reef safe. Will set up cleaning stations for fish.",
    description: "Iconic reef shrimp that cleans parasites from fish.",
    lifespan_years: 3,
    origin_region: "Indo-Pacific",
    habitat: "Coral reefs, cleaning stations",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Molting Issues"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Fish will line up for cleaning", "Hardy and active"],
    fun_facts: ["Will clean your hands if you let them!"],
    aliases: ["Skunk Cleaner Shrimp", "Pacific Cleaner Shrimp"]
  },
  {
    common_name: "Peppermint Shrimp",
    scientific_name: "Lysmata wurdemanni",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - aiptasia, detritus, meaty foods",
    compatibility_notes: "Great for aiptasia control. Reef safe.",
    description: "Red and white striped shrimp known for eating pest anemones.",
    lifespan_years: 2,
    origin_region: "Caribbean, Western Atlantic",
    habitat: "Reef crevices",
    group_behavior: "small_group",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily if no aiptasia",
    common_diseases: ["Molting Issues"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Keep multiple for better aiptasia control", "Shy - mostly nocturnal"],
    fun_facts: ["Natural aiptasia control - better than chemicals"],
    aliases: ["Veined Shrimp"]
  },
  {
    common_name: "Fire Shrimp",
    scientific_name: "Lysmata debelius",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - meaty foods, pellets, flakes",
    compatibility_notes: "Shy but reef safe. One of the most beautiful shrimp.",
    description: "Stunning blood-red shrimp with white antenna and legs.",
    lifespan_years: 3,
    origin_region: "Indo-Pacific",
    habitat: "Reef caves and overhangs",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Molting Issues"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Provide caves for hiding", "More shy than cleaner shrimp"],
    fun_facts: ["Also acts as a cleaner - fish may visit for cleaning"],
    aliases: ["Blood Shrimp", "Scarlet Cleaner Shrimp"]
  },
  {
    common_name: "Emerald Crab",
    scientific_name: "Mithraculus sculptus",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 2.5,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - bubble algae, various algae, meaty foods",
    compatibility_notes: "Generally reef safe. Excellent bubble algae control.",
    description: "Green crab prized for eating nuisance bubble algae.",
    lifespan_years: 4,
    origin_region: "Caribbean",
    habitat: "Coral reefs, rubble zones",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "If no bubble algae, supplement 2-3x weekly",
    common_diseases: ["Molting Issues"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Best natural bubble algae control", "May become opportunistic if underfed"],
    fun_facts: ["One of few animals that readily eats bubble algae"],
    aliases: ["Emerald Mithrax Crab", "Green Clinging Crab"]
  },
  {
    common_name: "Turbo Snail",
    scientific_name: "Turbo fluctuosa",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 2.5,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - film algae, hair algae, diatoms",
    compatibility_notes: "Excellent algae eater. May knock over unstable coral frags.",
    description: "Large, powerful algae-eating snail for marine tanks.",
    lifespan_years: 3,
    origin_region: "Mexico, Gulf of California",
    habitat: "Rocky intertidal zones",
    group_behavior: "solitary",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "herbivore",
    feeding_frequency: "Constant grazing",
    common_diseases: ["Starvation after algae depleted"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Very effective algae control", "May starve if tank has no algae"],
    fun_facts: ["Can flip itself back over unlike some snails"],
    aliases: ["Mexican Turbo Snail"]
  },
  {
    common_name: "Nassarius Snail",
    scientific_name: "Nassarius vibex",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 1,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - detritus, uneaten food, deceased organisms",
    compatibility_notes: "Excellent sand bed cleaner. Burrows in sand.",
    description: "Active scavenger snail that keeps sand beds clean.",
    lifespan_years: 2,
    origin_region: "Caribbean, Western Atlantic",
    habitat: "Sandy substrate near reefs",
    group_behavior: "small_group",
    breeding_difficulty: "moderate",
    diet_type: "detritivore",
    feeding_frequency: "Scavenges constantly",
    common_diseases: ["Starvation"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Best sand bed cleaners", "Will emerge dramatically when food is added"],
    fun_facts: ["Can sense food from buried position and emerge quickly"],
    aliases: ["Nassarius Vibex Snail", "Super Tongan Nassarius"]
  },
  {
    common_name: "Tuxedo Urchin",
    scientific_name: "Mespilia globulus",
    type: "invertebrate",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - algae, nori, seaweed",
    compatibility_notes: "Reef safe. Carries debris for camouflage.",
    description: "Small, colorful urchin that disguises itself with shell fragments.",
    lifespan_years: 5,
    origin_region: "Indo-Pacific",
    habitat: "Shallow reef flats",
    group_behavior: "solitary",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "herbivore",
    feeding_frequency: "Constant grazing",
    common_diseases: ["Spine loss from poor water quality"],
    salinity_min: 1.023,
    salinity_max: 1.026,
    care_tips: ["Will decorate itself with loose items", "Great algae control"],
    fun_facts: ["Picks up shells and debris to wear as camouflage"],
    aliases: ["Blue Tuxedo Urchin", "Sphere Urchin"]
  }
];
