/**
 * Expanded Aquatic Plant Species Data
 * Sprint 28: Species Database Upgrade
 */

import type { SpeciesSeed } from "../seed-species-types";

export const plantsExpanded: SpeciesSeed[] = [
  // ============================================================================
  // STEM PLANTS
  // ============================================================================
  {
    common_name: "Rotala Rotundifolia",
    scientific_name: "Rotala rotundifolia",
    type: "plant",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 20,
    temp_min_f: 68,
    temp_max_f: 82,
    ph_min: 5.5,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate light, CO2 beneficial",
    compatibility_notes: "Fast-growing stem plant. Needs regular trimming.",
    description: "Popular stem plant that turns pink/red under high light.",
    lifespan_years: 0,
    origin_region: "Southeast Asia",
    habitat: "Rice paddies and wet areas",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 0,
    hardness_max_dgh: 15,
    care_tips: ["Pinker with high light and iron", "Propagate by cutting and replanting tops"],
    fun_facts: ["One of the easiest red plants to grow"],
    aliases: ["Dwarf Rotala", "Pink Rotala"]
  },
  {
    common_name: "Ludwigia Repens",
    scientific_name: "Ludwigia repens",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 20,
    temp_min_f: 59,
    temp_max_f: 79,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Photosynthetic - low to high light adaptable",
    compatibility_notes: "Hardy stem plant. Tolerates wide range of conditions.",
    description: "Easy red/green stem plant that thrives in most setups.",
    lifespan_years: 0,
    origin_region: "North and Central America",
    habitat: "Marshes and stream banks",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 20,
    care_tips: ["Turns redder under strong light", "Extremely adaptable"],
    fun_facts: ["Native to North America - one of few aquarium plants from US"],
    aliases: ["Creeping Primrose-Willow", "Red Ludwigia"]
  },
  {
    common_name: "Bacopa Caroliniana",
    scientific_name: "Bacopa caroliniana",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 16,
    temp_min_f: 59,
    temp_max_f: 86,
    ph_min: 5.0,
    ph_max: 8.0,
    diet: "Photosynthetic - low to moderate light",
    compatibility_notes: "Slow-growing, hardy stem plant.",
    description: "Thick-leaved stem plant with a pleasant lemon scent when crushed.",
    lifespan_years: 0,
    origin_region: "Southern United States",
    habitat: "Marshes and pond margins",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 1,
    hardness_max_dgh: 20,
    care_tips: ["Very slow growth", "Leaves smell like lemon when crushed"],
    fun_facts: ["Also known as Water Hyssop and used in traditional medicine"],
    aliases: ["Lemon Bacopa", "Water Hyssop"]
  },
  {
    common_name: "Cabomba Caroliniana",
    scientific_name: "Cabomba caroliniana",
    type: "plant",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 15,
    max_size_inches: 24,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate to high light",
    compatibility_notes: "Delicate, feathery plant. Needs good conditions.",
    description: "Beautiful feathery plant that creates a forest effect.",
    lifespan_years: 0,
    origin_region: "Americas",
    habitat: "Still and slow-moving waters",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Needs stable conditions", "Drops leaves if stressed"],
    fun_facts: ["Also known as fanwort due to fan-shaped leaves"],
    aliases: ["Green Cabomba", "Fanwort"]
  },
  // ============================================================================
  // CARPETING PLANTS
  // ============================================================================
  {
    common_name: "Dwarf Baby Tears",
    scientific_name: "Hemianthus callitrichoides",
    type: "plant",
    care_level: "expert",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 2,
    temp_min_f: 68,
    temp_max_f: 82,
    ph_min: 5.0,
    ph_max: 7.5,
    diet: "Photosynthetic - high light, CO2 required",
    compatibility_notes: "Demanding carpet plant. Requires high tech setup.",
    description: "The smallest aquarium plant, creates stunning grass-like carpet.",
    lifespan_years: 0,
    origin_region: "Cuba",
    habitat: "Rocky streambeds",
    group_behavior: "colony",
    breeding_difficulty: "difficult",
    diet_type: "photosynthetic",
    hardness_min_dgh: 0,
    hardness_max_dgh: 12,
    care_tips: ["Requires CO2 injection", "Very high light demanding"],
    fun_facts: ["Smallest aquarium plant leaves in the world"],
    aliases: ["HC Cuba", "HC", "Cuba"]
  },
  {
    common_name: "Dwarf Hairgrass",
    scientific_name: "Eleocharis parvula",
    type: "plant",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 6,
    temp_min_f: 50,
    temp_max_f: 86,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate to high light",
    compatibility_notes: "Grass-like carpet plant. Spreads via runners.",
    description: "Creates a natural lawn effect in the aquarium.",
    lifespan_years: 0,
    origin_region: "Worldwide",
    habitat: "Marshes and pond edges",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    hardness_min_dgh: 2,
    hardness_max_dgh: 15,
    care_tips: ["Spreads faster with CO2", "Trim regularly for dense carpet"],
    fun_facts: ["Can be grown emergent in terrariums"],
    aliases: ["DHG", "Dwarf Spike Rush"]
  },
  {
    common_name: "Monte Carlo",
    scientific_name: "Micranthemum tweediei",
    type: "plant",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 2,
    temp_min_f: 68,
    temp_max_f: 77,
    ph_min: 6.0,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate to high light",
    compatibility_notes: "Easier alternative to HC Cuba for carpet.",
    description: "Small-leaved carpet plant easier than HC Cuba.",
    lifespan_years: 0,
    origin_region: "Argentina",
    habitat: "Stream margins",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Can carpet without CO2 in high light", "More forgiving than HC Cuba"],
    fun_facts: ["Named after Monte Carlo region of Argentina"],
    aliases: ["New Large Pearl Grass", "Bacopita"]
  },
  // ============================================================================
  // ROSETTE PLANTS
  // ============================================================================
  {
    common_name: "Amazon Sword",
    scientific_name: "Echinodorus bleheri",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 20,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 6.5,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate light, root feeder",
    compatibility_notes: "Large background plant. Heavy root feeder.",
    description: "Classic aquarium centerpiece plant with broad leaves.",
    lifespan_years: 0,
    origin_region: "Amazon Basin",
    habitat: "River margins",
    group_behavior: "solitary",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Benefits from root tabs", "Can grow very large"],
    fun_facts: ["One of the first aquarium plants ever cultivated"],
    aliases: ["Sword Plant", "Amazon Sword Plant"]
  },
  {
    common_name: "Cryptocoryne Wendtii",
    scientific_name: "Cryptocoryne wendtii",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 10,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Photosynthetic - low to moderate light",
    compatibility_notes: "Hardy crypt. May melt when moved but recovers.",
    description: "Most popular crypt species, available in many color forms.",
    lifespan_years: 0,
    origin_region: "Sri Lanka",
    habitat: "Shaded forest streams",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 18,
    care_tips: ["May melt when first planted - don't remove, it will regrow", "Very adaptable"],
    fun_facts: ["Crypt melt is common but plant usually recovers stronger"],
    aliases: ["Crypt Wendtii", "Wendtii"]
  },
  {
    common_name: "Vallisneria",
    scientific_name: "Vallisneria spiralis",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 36,
    temp_min_f: 59,
    temp_max_f: 86,
    ph_min: 6.0,
    ph_max: 9.0,
    diet: "Photosynthetic - low to high light",
    compatibility_notes: "Fast-spreading background plant.",
    description: "Long ribbon-like leaves create flowing curtain effect.",
    lifespan_years: 0,
    origin_region: "Worldwide",
    habitat: "Lakes and slow rivers",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 5,
    hardness_max_dgh: 25,
    care_tips: ["Spreads via runners very fast", "Can take over tank if not controlled"],
    fun_facts: ["One of the oldest aquarium plants - used since 1800s"],
    aliases: ["Val", "Eelgrass", "Tape Grass"]
  },
  // ============================================================================
  // FLOATING PLANTS
  // ============================================================================
  {
    common_name: "Red Root Floater",
    scientific_name: "Phyllanthus fluitans",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 2,
    temp_min_f: 70,
    temp_max_f: 82,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Photosynthetic - moderate to high light",
    compatibility_notes: "Floating plant with red roots. Easy care.",
    description: "Beautiful floater with red roots and leaves that turn red under strong light.",
    lifespan_years: 0,
    origin_region: "South America",
    habitat: "Still and slow-moving waters",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 2,
    hardness_max_dgh: 15,
    care_tips: ["Leaves turn red under strong light", "Needs still surface - no agitation"],
    fun_facts: ["Roots absorb nutrients and provide shrimp grazing area"],
    aliases: ["RRF"]
  },
  {
    common_name: "Frogbit",
    scientific_name: "Limnobium laevigatum",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 4,
    temp_min_f: 64,
    temp_max_f: 86,
    ph_min: 6.0,
    ph_max: 8.0,
    diet: "Photosynthetic - low to high light",
    compatibility_notes: "Easy floating plant with attractive round leaves.",
    description: "Lily pad-like floating plant with dangling roots.",
    lifespan_years: 0,
    origin_region: "Americas",
    habitat: "Still waters",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 2,
    hardness_max_dgh: 18,
    care_tips: ["Can multiply quickly", "Good at removing excess nutrients"],
    fun_facts: ["Roots provide hiding spots for fish fry"],
    aliases: ["Amazon Frogbit", "South American Frogbit"]
  },
  {
    common_name: "Duckweed",
    scientific_name: "Lemna minor",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 1,
    max_size_inches: 0.25,
    temp_min_f: 50,
    temp_max_f: 86,
    ph_min: 5.0,
    ph_max: 9.0,
    diet: "Photosynthetic - any light",
    compatibility_notes: "Extremely fast-growing. Can take over surface.",
    description: "Tiny floating plant that doubles in days.",
    lifespan_years: 0,
    origin_region: "Worldwide",
    habitat: "Still freshwater everywhere",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 0,
    hardness_max_dgh: 30,
    care_tips: ["Grows so fast it's often considered a pest", "Excellent nutrient export"],
    fun_facts: ["One of the fastest growing plants on Earth"],
    aliases: ["Common Duckweed"]
  },
  // ============================================================================
  // MOSSES
  // ============================================================================
  {
    common_name: "Java Moss",
    scientific_name: "Taxiphyllum barbieri",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 4,
    temp_min_f: 59,
    temp_max_f: 86,
    ph_min: 5.0,
    ph_max: 8.0,
    diet: "Photosynthetic - any light level",
    compatibility_notes: "Extremely hardy. Attach to hardscape.",
    description: "The classic aquarium moss, nearly impossible to kill.",
    lifespan_years: 0,
    origin_region: "Southeast Asia",
    habitat: "Streams and river banks",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 0,
    hardness_max_dgh: 20,
    care_tips: ["Attach to wood/rock with thread or glue", "Trim to encourage dense growth"],
    fun_facts: ["Provides ideal breeding habitat for shrimp"],
    aliases: []
  },
  {
    common_name: "Christmas Moss",
    scientific_name: "Vesicularia montagnei",
    type: "plant",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 4,
    temp_min_f: 65,
    temp_max_f: 77,
    ph_min: 5.0,
    ph_max: 7.5,
    diet: "Photosynthetic - low to moderate light",
    compatibility_notes: "Prettier than Java moss but slightly more demanding.",
    description: "Moss with triangular fronds that resemble Christmas tree branches.",
    lifespan_years: 0,
    origin_region: "Asia, India",
    habitat: "Humid forests, stream banks",
    group_behavior: "colony",
    breeding_difficulty: "easy",
    diet_type: "photosynthetic",
    hardness_min_dgh: 3,
    hardness_max_dgh: 15,
    care_tips: ["Prefers cooler water", "More structured than Java moss"],
    fun_facts: ["Named for Christmas tree-like growth pattern"],
    aliases: ["Xmas Moss"]
  },
  {
    common_name: "Flame Moss",
    scientific_name: "Taxiphyllum sp. 'Flame'",
    type: "plant",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 5,
    max_size_inches: 6,
    temp_min_f: 68,
    temp_max_f: 82,
    ph_min: 5.5,
    ph_max: 7.5,
    diet: "Photosynthetic - moderate light",
    compatibility_notes: "Grows upward like flames. Attach to hardscape.",
    description: "Unique moss that grows vertically like green flames.",
    lifespan_years: 0,
    origin_region: "Southeast Asia",
    habitat: "Humid forests",
    group_behavior: "colony",
    breeding_difficulty: "moderate",
    diet_type: "photosynthetic",
    hardness_min_dgh: 2,
    hardness_max_dgh: 12,
    care_tips: ["Grows upward naturally", "Creates unique vertical texture"],
    fun_facts: ["One of the few mosses that grows vertically"],
    aliases: []
  }
];
