/**
 * Expanded Saltwater Fish Species Data
 * Sprint 28: Species Database Upgrade
 */

import type { SpeciesSeed } from "../seed-species-types";

export const saltwaterFishExpanded: SpeciesSeed[] = [
  // ============================================================================
  // CLOWNFISH
  // ============================================================================
  {
    common_name: "Percula Clownfish",
    scientific_name: "Amphiprion percula",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 4,
    temp_min_f: 74,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - marine pellets, frozen mysis, enriched brine shrimp",
    compatibility_notes: "Hardy and beginner-friendly. Pairs well with anemones but doesn't require one.",
    description: "The true 'Nemo' clownfish with distinct black outlining.",
    lifespan_years: 15,
    origin_region: "Papua New Guinea, Solomon Islands",
    habitat: "Coral reefs with host anemones",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich", "Brooklynella", "Marine Velvet"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Very similar to ocellaris - often mislabeled", "Tank-bred specimens are hardier"],
    fun_facts: ["Can change sex - largest becomes female", "Immune to anemone stings"],
    aliases: ["True Percula", "Orange Clownfish"]
  },
  {
    common_name: "Maroon Clownfish",
    scientific_name: "Premnas biaculeatus",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "aggressive",
    min_tank_size_gallons: 30,
    max_size_inches: 6,
    temp_min_f: 74,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - marine pellets, frozen foods, occasional vegetable matter",
    compatibility_notes: "Most aggressive clownfish. Female can become very territorial.",
    description: "Largest and most aggressive clownfish with bold maroon coloring.",
    lifespan_years: 20,
    origin_region: "Indo-Pacific",
    habitat: "Bubble tip anemones on reefs",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich", "Brooklynella"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Females can become very large and aggressive", "Best kept as a pair"],
    fun_facts: ["Has cheek spines unlike other clownfish", "Gold stripe variety is highly prized"],
    aliases: ["Spine-Cheek Clownfish", "Gold Stripe Maroon"]
  },
  {
    common_name: "Tomato Clownfish",
    scientific_name: "Amphiprion frenatus",
    type: "saltwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 30,
    max_size_inches: 5,
    temp_min_f: 74,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - marine pellets, frozen foods",
    compatibility_notes: "Hardy but can be territorial. One of the tougher clownfish.",
    description: "Robust red-orange clownfish with a single white head bar.",
    lifespan_years: 18,
    origin_region: "Western Pacific",
    habitat: "Coral reefs",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich", "Brooklynella"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Very hardy species", "Can bully other fish if kept alone"],
    fun_facts: ["Juveniles have three bars, adults have one"],
    aliases: ["Bridled Clownfish", "Red Clownfish"]
  },
  // ============================================================================
  // TANGS
  // ============================================================================
  {
    common_name: "Blue Tang",
    scientific_name: "Paracanthurus hepatus",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 125,
    max_size_inches: 12,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - nori, marine algae, spirulina-based foods",
    compatibility_notes: "Prone to ich. Needs lots of swimming room.",
    description: "The famous 'Dory' fish with vibrant blue body and yellow tail.",
    lifespan_years: 20,
    origin_region: "Indo-Pacific",
    habitat: "Coral reefs, often near caves",
    group_behavior: "small_group",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "herbivore",
    feeding_frequency: "3x daily",
    common_diseases: ["Marine Ich", "HLLE", "Marine Velvet"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Very prone to ich - quarantine carefully", "Needs lots of swimming space"],
    fun_facts: ["Can wedge itself into crevices when sleeping", "Changes color when stressed"],
    aliases: ["Regal Tang", "Hippo Tang", "Palette Surgeonfish", "Dory Fish"]
  },
  {
    common_name: "Kole Tang",
    scientific_name: "Ctenochaetus strigosus",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 75,
    max_size_inches: 7,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - nori, algae, marine vegetable foods",
    compatibility_notes: "One of the more peaceful tangs. Excellent algae grazer.",
    description: "Brown tang with distinctive eye stripe, great for algae control.",
    lifespan_years: 15,
    origin_region: "Hawaii, Central Pacific",
    habitat: "Shallow reef areas",
    group_behavior: "solitary",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "herbivore",
    feeding_frequency: "3x daily",
    common_diseases: ["Marine Ich", "HLLE"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Best tang for smaller reef tanks", "Constantly grazes on rockwork"],
    fun_facts: ["Has comb-like teeth for scraping algae"],
    aliases: ["Yellow Eye Tang", "Yelloweye Bristletooth"]
  },
  {
    common_name: "Powder Blue Tang",
    scientific_name: "Acanthurus leucosternon",
    type: "saltwater",
    care_level: "expert",
    temperament: "aggressive",
    min_tank_size_gallons: 125,
    max_size_inches: 9,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - nori, algae, spirulina",
    compatibility_notes: "Beautiful but challenging. Aggressive toward similar fish.",
    description: "Stunning light blue tang with yellow dorsal and dark face mask.",
    lifespan_years: 15,
    origin_region: "Indian Ocean",
    habitat: "Surge zones of coral reefs",
    group_behavior: "solitary",
    breeding_difficulty: "impossible_in_captivity",
    diet_type: "herbivore",
    feeding_frequency: "3x daily",
    common_diseases: ["Marine Ich", "HLLE", "Marine Velvet"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Very susceptible to disease", "Needs pristine water quality"],
    fun_facts: ["One of the most beautiful but challenging tangs"],
    aliases: ["Powder Blue Surgeonfish"]
  },
  // ============================================================================
  // WRASSES
  // ============================================================================
  {
    common_name: "Six Line Wrasse",
    scientific_name: "Pseudocheilinus hexataenia",
    type: "saltwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 30,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, brine shrimp, small pellets",
    compatibility_notes: "Can be territorial. May harass smaller or timid fish.",
    description: "Hardy, colorful wrasse with distinctive horizontal purple stripes.",
    lifespan_years: 8,
    origin_region: "Indo-Pacific",
    habitat: "Coral reefs among rubble",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich", "Marine Velvet"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Add last to reduce aggression", "Good at eating flatworms and pyramidellid snails"],
    fun_facts: ["One of the few wrasses safe for reef tanks"],
    aliases: ["Sixline Wrasse"]
  },
  {
    common_name: "Fairy Wrasse",
    scientific_name: "Cirrhilabrus lubbocki",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 55,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 79,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, enriched brine shrimp, quality pellets",
    compatibility_notes: "Very peaceful wrasse. Keep one male with several females.",
    description: "Peaceful, colorful wrasse that stays small and reef-safe.",
    lifespan_years: 6,
    origin_region: "Western Pacific",
    habitat: "Outer reef slopes",
    group_behavior: "small_group",
    breeding_difficulty: "difficult",
    diet_type: "carnivore",
    feeding_frequency: "2-3x daily",
    common_diseases: ["Marine Ich", "Jumping out of tank"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Good jumper - needs tight-fitting lid", "Males flash colors to females"],
    fun_facts: ["Males display amazing colors when courting"],
    aliases: ["Lubbock's Fairy Wrasse"]
  },
  {
    common_name: "Yellow Coris Wrasse",
    scientific_name: "Halichoeres chrysus",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 50,
    max_size_inches: 5,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, brine shrimp, chopped seafood",
    compatibility_notes: "Very peaceful. One of the best wrasses for beginners.",
    description: "Bright yellow wrasse that hunts pests in the sand bed.",
    lifespan_years: 7,
    origin_region: "Indo-Pacific",
    habitat: "Sandy reef areas",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Needs sand bed to sleep in", "Excellent flatworm and bristleworm hunter"],
    fun_facts: ["Buries itself in sand at night to sleep"],
    aliases: ["Golden Wrasse", "Canary Wrasse"]
  },
  // ============================================================================
  // GOBIES & BLENNIES
  // ============================================================================
  {
    common_name: "Watchman Goby",
    scientific_name: "Cryptocentrus cinctus",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 4,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, brine shrimp, sinking pellets",
    compatibility_notes: "Very peaceful. Often pairs with pistol shrimp.",
    description: "Hardy goby that sifts sand and can form symbiotic pair with pistol shrimp.",
    lifespan_years: 5,
    origin_region: "Indo-Pacific",
    habitat: "Sandy reef areas with burrows",
    group_behavior: "pair",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Provide sand bed for burrowing", "Add pistol shrimp for fascinating symbiosis"],
    fun_facts: ["Acts as lookout while pistol shrimp maintains burrow"],
    aliases: ["Yellow Watchman Goby", "Yellow Prawn Goby"]
  },
  {
    common_name: "Diamond Goby",
    scientific_name: "Valenciennea puellaris",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 6,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen foods, copepods from sand bed",
    compatibility_notes: "Needs established sand bed with microfauna.",
    description: "Beautiful sand-sifting goby with orange spots and diamond markings.",
    lifespan_years: 5,
    origin_region: "Indo-Pacific",
    habitat: "Sandy reef flats",
    group_behavior: "pair",
    breeding_difficulty: "difficult",
    diet_type: "carnivore",
    feeding_frequency: "Constant sand sifting + 1x daily",
    common_diseases: ["Starvation", "Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Needs mature tank with copepod population", "May starve without supplemental feeding"],
    fun_facts: ["Constantly sifts sand for food, keeping sand bed clean"],
    aliases: ["Orange Spotted Goby", "Orange Diamond Goby"]
  },
  {
    common_name: "Midas Blenny",
    scientific_name: "Ecsenius midas",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 5,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - algae, frozen foods, quality pellets",
    compatibility_notes: "Peaceful and interesting personality. Great reef fish.",
    description: "Gorgeous golden blenny that hovers above the reef like a mermaid.",
    lifespan_years: 5,
    origin_region: "Indo-Pacific, Red Sea",
    habitat: "Reef faces and slopes",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Provide caves for hiding", "Often mimics anthias behavior"],
    fun_facts: ["Can change color from yellow to blue depending on mood"],
    aliases: ["Golden Blenny", "Lyretail Blenny"]
  },
  {
    common_name: "Tailspot Blenny",
    scientific_name: "Ecsenius stigmatura",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 10,
    max_size_inches: 2.5,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Herbivore - algae, spirulina, marine algae sheets",
    compatibility_notes: "Very peaceful algae eater perfect for nano reef tanks.",
    description: "Cute small blenny with distinctive spot near tail base.",
    lifespan_years: 4,
    origin_region: "Western Pacific",
    habitat: "Shallow coral reefs",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "herbivore",
    feeding_frequency: "2x daily + algae grazing",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Excellent algae eater for nano tanks", "Perches on rocks with great personality"],
    fun_facts: ["One of the best small blennies for reef tanks"],
    aliases: []
  },
  // ============================================================================
  // CARDINALFISH
  // ============================================================================
  {
    common_name: "Pajama Cardinalfish",
    scientific_name: "Sphaeramia nematoptera",
    type: "saltwater",
    care_level: "beginner",
    temperament: "peaceful",
    min_tank_size_gallons: 20,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, brine shrimp, small pellets",
    compatibility_notes: "Very peaceful. Can be kept in groups.",
    description: "Unique cardinalfish with polka dots and striped pattern like pajamas.",
    lifespan_years: 5,
    origin_region: "Western Pacific",
    habitat: "Sheltered reef areas among corals",
    group_behavior: "small_group",
    min_school_size: 3,
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Nocturnal - most active at dawn and dusk", "Hides among branches during day"],
    fun_facts: ["Males are mouthbrooders - carry eggs in their mouth"],
    aliases: ["Polka Dot Cardinalfish", "Spotted Cardinalfish"]
  },
  {
    common_name: "Banggai Cardinalfish",
    scientific_name: "Pterapogon kauderni",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "peaceful",
    min_tank_size_gallons: 30,
    max_size_inches: 3,
    temp_min_f: 75,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, enriched brine shrimp, quality pellets",
    compatibility_notes: "Peaceful but can be aggressive to conspecifics. Keep in pairs.",
    description: "Stunning black and silver striped cardinalfish from one small island.",
    lifespan_years: 5,
    origin_region: "Banggai Islands, Indonesia",
    habitat: "Shallow reef areas, often with urchins",
    group_behavior: "pair",
    breeding_difficulty: "easy",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich", "Internal parasites"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["Best kept in pairs", "Males mouthbrood - easy to breed in captivity"],
    fun_facts: ["Endemic to tiny area - captive breeding is conservation effort"],
    aliases: ["Kaudern's Cardinalfish", "Banggai Cardinal"]
  },
  // ============================================================================
  // ANGELFISH (DWARF)
  // ============================================================================
  {
    common_name: "Flame Angelfish",
    scientific_name: "Centropyge loricula",
    type: "saltwater",
    care_level: "intermediate",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 55,
    max_size_inches: 4,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - spirulina, marine algae, frozen mysis, angel formula",
    compatibility_notes: "May nip at some corals. Reef-safe with caution.",
    description: "Stunning bright red-orange dwarf angel with black vertical bars.",
    lifespan_years: 7,
    origin_region: "Central Pacific, Hawaii",
    habitat: "Coral reefs with hiding spots",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "2-3x daily",
    common_diseases: ["Marine Ich", "HLLE"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["May nip at LPS and clam mantles", "Individual behavior varies"],
    fun_facts: ["One of the most popular dwarf angels in the hobby"],
    aliases: ["Flame Angel", "Flaming Angelfish"]
  },
  {
    common_name: "Coral Beauty Angelfish",
    scientific_name: "Centropyge bispinosa",
    type: "saltwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 55,
    max_size_inches: 4,
    temp_min_f: 72,
    temp_max_f: 82,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Omnivore - spirulina, marine algae, frozen foods, angel formula",
    compatibility_notes: "One of the most reef-safe dwarf angels. Hardy species.",
    description: "Beautiful purple and orange dwarf angel, one of the hardiest.",
    lifespan_years: 10,
    origin_region: "Indo-Pacific",
    habitat: "Coral reefs, lagoons",
    group_behavior: "solitary",
    breeding_difficulty: "difficult",
    diet_type: "omnivore",
    feeding_frequency: "2-3x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["One of the hardiest dwarf angels", "Generally reef-safe"],
    fun_facts: ["Color intensity varies by location of origin"],
    aliases: ["Twospined Angelfish", "Dusky Angelfish"]
  },
  // ============================================================================
  // DOTTYBACKS & ASSESSORS
  // ============================================================================
  {
    common_name: "Orchid Dottyback",
    scientific_name: "Pseudochromis fridmani",
    type: "saltwater",
    care_level: "beginner",
    temperament: "semi_aggressive",
    min_tank_size_gallons: 30,
    max_size_inches: 3,
    temp_min_f: 72,
    temp_max_f: 80,
    ph_min: 8.1,
    ph_max: 8.4,
    diet: "Carnivore - frozen mysis, brine shrimp, quality pellets",
    compatibility_notes: "Can be aggressive to similar fish. Generally reef-safe.",
    description: "Vibrant purple dottyback from the Red Sea.",
    lifespan_years: 7,
    origin_region: "Red Sea",
    habitat: "Reef walls and crevices",
    group_behavior: "solitary",
    breeding_difficulty: "moderate",
    diet_type: "carnivore",
    feeding_frequency: "2x daily",
    common_diseases: ["Marine Ich"],
    salinity_min: 1.020,
    salinity_max: 1.026,
    care_tips: ["One of the least aggressive dottybacks", "Provide hiding caves"],
    fun_facts: ["Can eat bristleworms and small pests"],
    aliases: ["Fridman's Dottyback", "Purple Pseudochromis"]
  }
];
