-- ============================================================================
-- Proactive Alerts Table
-- Created: February 8, 2026
-- Description: Store proactive alerts generated by AI trend analysis
-- Spec: 17_AI_Proactive_Intelligence_Spec.md
-- ============================================================================

-- Proactive alerts table
CREATE TABLE IF NOT EXISTS proactive_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tank_id UUID NOT NULL REFERENCES tanks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parameter VARCHAR(50) NOT NULL, -- e.g., 'pH', 'ammonia', 'nitrate'
  current_value DECIMAL(8,2),
  unit VARCHAR(10),
  trend_direction VARCHAR(20) NOT NULL CHECK (trend_direction IN ('increasing', 'decreasing', 'stable', 'spiking')),
  trend_rate DECIMAL(8,4), -- Rate of change per day/week
  projection_text TEXT, -- AI-generated projection: "pH will hit danger zone in 2 weeks"
  likely_cause TEXT, -- AI-generated correlation: "This spike happened 2 days after you added 3 new fish"
  suggested_action TEXT, -- AI-generated action: "I've drafted a water change reminder for tomorrow"
  severity VARCHAR(20) NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'alert')),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'dismissed', 'resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  dismissed_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  resolved_by_action_id UUID -- Links to action that resolved the alert
);

-- Indexes for efficient queries
CREATE INDEX idx_proactive_alerts_tank ON proactive_alerts(tank_id);
CREATE INDEX idx_proactive_alerts_user ON proactive_alerts(user_id);
CREATE INDEX idx_proactive_alerts_status ON proactive_alerts(status) WHERE status = 'active';
CREATE INDEX idx_proactive_alerts_created ON proactive_alerts(created_at DESC);

-- Enable RLS
ALTER TABLE proactive_alerts ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own proactive alerts"
  ON proactive_alerts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own proactive alerts"
  ON proactive_alerts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own proactive alerts"
  ON proactive_alerts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own proactive alerts"
  ON proactive_alerts FOR DELETE
  USING (auth.uid() = user_id);

-- Comment
COMMENT ON TABLE proactive_alerts IS 'Proactive alerts generated by AI trend analysis (Spec 17)';
